### Numpy

NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices,
along with a collection of mathematical functions to operate on these data structures. In this lesson, we will
cover the basics of NumPy, focusing on arrays and vectorized operations.

In [3]:
!pip install -r ../requirements.txt

  Using cached pandas-3.0.3-cp312-cp312-win_amd64.whl.metadata (19 kB)
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
    --------------------------------------- 0.3/12.4 MB ? eta -:--:--
   --- ------------------------------------ 1.0/12.4 MB 3.6 MB/s eta 0:00:04
   ------ --------------------------------- 2.1/12.4 MB 3.9 MB/s eta 0:00:03
   -------- ------------------------------- 2.6/12.4 MB 3.8 MB/s eta 0:00:03
   ----------- ---------------------------- 3.7/12.4 MB 3.9 MB/s eta 0:00:03
   ---------------- ----------------------- 5.0/12.4 MB 4.3 MB/s eta 0:00:02
   ------------------ --------------------- 5.8/12.4 MB 4.3 MB/s eta 0:00:02
   ----------------------- ---------------- 7.3/12.4 MB 4.7 MB/s eta 0:00:02
   -------------------------- ------------- 8.1/12.4 MB 4.5 MB/s eta 0:00:01
   ------------------------------ --------- 9.4/12.4 MB 4.7 MB/s eta 0:00:01
   --------------------------------- ------ 10.5/12.4 MB 4.9 MB/s eta 0:00:01
   ---------------

In [7]:
import numpy as np 

## create arrays using numpy 
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

[1 2 3 4 5]
[1 2 3 4 5]


In [8]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [10]:
arr3 = np.array([[1,2,3],[4,5,6]])
arr3.shape

(2, 3)

In [12]:
np.arange(0, 10, 2).reshape(1,5)

array([[0, 2, 4, 6, 8]])

In [13]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
##identity matrix 

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:", arr)
print("Shape:", arr.shape)
print("Number of dimensions:", arr.ndim)
print("Size (number of elements):", arr.size)
print("Data type:", arr.dtype)
print("Item size (in bytes):", arr.itemsize)

Array: [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


In [18]:
## Numpy vectorized operations

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

### element wise addition
print("Addition" , arr1 + arr2)

Addition [11 22 33 44 55]


In [19]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

print("Subtraction:" , arr1 - arr2)

Subtraction: [ -9 -18 -27 -36 -45]


In [20]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

print("Multiplication:" , arr1 *  arr2)

Multiplication: [ 10  40  90 160 250]


In [21]:
## Universal Functions 

arr = np.array([1, 2, 3, 4, 5])
## square root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

## Sine
print(np.sin(arr))

##natural logarithm
print(np.log(arr))


[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [ ]:
## array slicing and indexing

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
print(arr[0][0])

1


In [30]:
arr[1:,1:]
print(arr[0:1,1:])

[[2 3]]


In [33]:
## Modify elements 

arr[0][0] = 100
print(arr)

arr[1:] = 100
print(arr)

[[100   2   3]
 [100 100 100]
 [100 100 100]]
[[100   2   3]
 [100 100 100]
 [100 100 100]]


In [34]:
## statistics -- normalization 

## to change the mean of 0 and standard deviation of 1, we can use the following formula:

data = np.array([1, 2, 3, 4, 5])

mean = np.mean(data)
std_dev = np.std(data)

normalized_data = (data - mean) / std_dev
print("Normalized Data:", normalized_data)

Normalized Data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [36]:
data = np.array([1, 2, 3, 4, 5])

## Mean

mean = np.mean(data)
print("Mean:", mean)

## Variance
var = np.var(data)
print("Variance:", var)

## Standard Deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

## Median
median = np.median(data)
print("Median:", median)

Mean: 3.0
Variance: 2.0
Standard Deviation: 1.4142135623730951
Median: 3.0


In [37]:
## Loginal Operations

data = np.array([1, 2, 3, 4, 5])

data > 2

array([False, False,  True,  True,  True])